In [3]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [4]:
conditions = pd.read_csv("../data/raw/conditions.csv")
encounters = pd.read_csv("../data/raw/encounters.csv")
patients = pd.read_csv("../data/raw/patients.csv")

In [5]:
print("Conditions shape: ", conditions.shape)
print("Encounters shape: ", encounters.shape)
print("Patients shape: ", patients.shape)

Conditions shape:  (114544, 6)
Encounters shape:  (321528, 15)
Patients shape:  (12352, 25)

In [6]:
print("DADOS DE PACIENTES")
display(patients.head(2), patients.tail(2))

print("\nDADOS DE ENCONTROS (CONSULTA MÉDICA OU IDA AO HOSPITAL)")
display(encounters.head(2), encounters.tail(2))

print("\nINFORMAÇÕES GERAIS DOS PACIENTES, INCLUINDO SOCIAIS")
display(conditions.head(2), conditions.tail(2))

DADOS DE PACIENTES

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
0,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,2017-08-24,NaN,999-68-6630,NaN,NaN,NaN,Jacinto644,Kris249,NaN,NaN,NaN,white,nonhispanic,M,Beverly Massachusetts US,888 Hickle Ferry Suite 38,Springfield,Massachusetts,Hampden County,1106.0,42.151961,-72.598959,8446.49,1499.08
1,067318a4-db8f-447f-8b6e-f2f61e9baaa5,2016-08-01,NaN,999-15-5895,NaN,NaN,NaN,Alva958,Krajcik437,NaN,NaN,NaN,white,nonhispanic,F,Boston Massachusetts US,1048 Skiles Trailer,Walpole,Massachusetts,Norfolk County,2081.0,42.177370,-71.281353,89893.40,1845.72

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE
12350,435be43f-cb57-442f-aeb2-51018b030ed0,1918-10-20,NaN,999-26-4571,S99995011,X51104300X,Ms.,Cherlyn665,Quitzon246,NaN,NaN,S,white,nonhispanic,F,Holyoke Massachusetts US,237 Miller Avenue,Waltham,Massachusetts,Middlesex County,2452.0,42.366768,-71.196715,1585631.29,32006.97
12351,2712205f-755e-4897-acb3-926895b7d635,1941-02-11,NaN,999-57-4019,S99932976,X25566175X,Mr.,Emory494,Turcotte120,NaN,NaN,S,white,nonhispanic,M,Medford Massachusetts US,595 Zulauf Parade Suite 56,Bourne,Massachusetts,Barnstable County,2532.0,41.721661,-70.587214,1689239.58,790451.35

DADOS DE ENCONTROS (CONSULTA MÉDICA OU IDA AO HOSPITAL)

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,d5ee30a9-362f-429e-a87a-ee38d999b0a5,2019-02-16T01:02:32Z,2019-02-16T01:17:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,5103c940-0c08-392f-95cd-446e0cea042a,e2c226c2-3e1e-3d0b-b997-ce9544c10528,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,outpatient,185345009,Encounter for symptom,129.16,129.16,69.16,65363002.0,Otitis media
1,6a74fdef-2287-44bf-b9e7-18012376faca,2019-08-02T01:02:32Z,2019-08-02T01:32:32Z,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,0b9f3f7c-8ab6-30a5-b3ae-4dc0e0c00cb3,87c33fc5-3fd1-3c52-815a-b89a1623bb3a,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,wellness,410620009,Well child visit (procedure),129.16,129.16,129.16,NaN,NaN

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
321526,f69323ee-fc33-45ff-94ba-914acde61601,2020-05-22T06:03:58Z,2020-05-22T06:18:58Z,2712205f-755e-4897-acb3-926895b7d635,d5117822-5756-389d-9547-891a372d580f,5ed53ed3-568e-3f70-9797-49ebdc4a74e9,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,185347001,Encounter for problem (procedure),129.16,129.16,89.16,NaN,NaN
321527,874117a4-16a4-4b86-b268-b8b9e7e72af7,2020-05-25T06:03:58Z,2020-05-25T08:18:58Z,2712205f-755e-4897-acb3-926895b7d635,d5117822-5756-389d-9547-891a372d580f,5ed53ed3-568e-3f70-9797-49ebdc4a74e9,7caa7254-5050-3b5e-9eae-bd5ea30e809c,ambulatory,185347001,Encounter for problem (procedure),129.16,129.16,89.16,NaN,NaN

INFORMAÇÕES GERAIS DOS PACIENTES, INCLUINDO SOCIAIS

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
0,2019-02-15,2019-08-01,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,d5ee30a9-362f-429e-a87a-ee38d999b0a5,65363002,Otitis media
1,2019-10-30,2020-01-30,f0f3bc8d-ef38-49ce-a2bd-dfdda982b271,8bca6d8a-ab80-4cbf-8abb-46654235f227,65363002,Otitis media

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
114542,2020-03-04,2020-03-04,2712205f-755e-4897-acb3-926895b7d635,a18d0f16-bc12-4897-8844-8c3ebc2464fc,840544004,Suspected COVID-19
114543,2020-03-04,2020-04-01,2712205f-755e-4897-acb3-926895b7d635,a18d0f16-bc12-4897-8844-8c3ebc2464fc,840539006,COVID-19

In [7]:
conditions["DESCRIPTION"].head(20)

0                             Otitis media
1                             Otitis media
2                          Fever (finding)
3                       Suspected COVID-19
4                                 COVID-19
5                          Sprain of ankle
6                          Cough (finding)
7                 Sputum finding (finding)
8               Diarrhea symptom (finding)
9                          Fever (finding)
10                      Suspected COVID-19
11                                COVID-19
12    Streptococcal sore throat (disorder)
13                            Hypertension
14              Viral sinusitis (disorder)
15                      Headache (finding)
16                         Cough (finding)
17                       Fatigue (finding)
18                        Nausea (finding)
19              Vomiting symptom (finding)
Name: DESCRIPTION, dtype: str